import { Inter } from 'next/font/google'
import './globals.css'
import {Navbar} from "#/navbar/Navbar";
import Script from "next/script";
import Head from "next/head"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <Head>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
                  integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
                  crossOrigin="anonymous" referrerpolicy="no-referrer"/>
        </Head>

        <body className={inter.className}>
            <Script src="https://cdn.lordicon.com/lordicon.js"></Script>
            <Navbar/>
            {children}
        </body>
        </html>
    )
}
