import { Inter } from 'next/font/google'
import './globals.css'
import {Navbar} from "@/component/Navbar";
import Script from "next/script";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <Script src="https://cdn.lordicon.com/lordicon.js" async></Script>
      <Navbar/>
      {children}
      </body>
    </html>
)
}
